### PR TITLE
Change node sets to be str/int's instead of str/vec<int>'s.

### PR DESCRIPTION
**Pull request by luciansmith**
The only issue is that I'm not sure how to add log error messages when I return -1.  I think everything else should be OK?

### CODE REVIEW

**Comment by luciansmith** [comment]
Oh, I didn't change the docs, either.

**Review by adelhpour — COMMENTED** [review]
This code:

`const char **lockedNode = lockedNodes[I];`
`const char *id = lockedNode[0];`
`int index = atoi(lockedNode[1]);`
`lockedNodesSet.insert(std::make_pair(id, index));`

does not look good to me. The first element is the node id, the second element is the size of the array of graphical object indices, and the ones that come after are the indices. Writing it in this way will lead to losing all those indices.

**Comment by luciansmith** [comment]
No, that's the design change, that I put into the C API as well, or at least it's supposed to be.  [["S1", "1"], ["S1", "2"], ["S3", "0"], ... ]

**Comment by adelhpour** [comment]
Oh, I got it. There is a need to apply the changes to the Python layer. I just did it. Let's see if it works well.

**Comment by adelhpour** [comment]
Everything sounds good. I'll just merge it.

**Pull request merged**
